server {
    listen 80;

    # 1. Where the build files are
    root /usr/share/nginx/html;
    index index.html;

    # 2. The Magic Fix for React Router
    location / {
        # Try to find the file ($uri), then the folder ($uri/),
        # if neither exists, serve index.html
        try_files $uri $uri/ /index.html;
    }
}